<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Template\**\*">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <PackageReference Include="DocX" Version="2.4.0" />
    <PackageReference Include="EasyConveyor" Version="1.0.0" />
    <PackageReference Include="EPPlus" Version="6.2.2" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Polybioz.HtmlRenderer.PdfSharp.Core" Version="1.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    <PackageReference Include="SendGrid" Version="9.28.1" />
    <PackageReference Include="SendGrid.SmtpApi" Version="1.4.6" />
    <PackageReference Include="SendGrid.Extensions.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="SendGrid.CSharp.HTTP.Client" Version="3.4.12" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SendGrid" Version="3.0.3" />
    <PackageReference Include="AspNetCore.HealthChecks.SendGrid" Version="7.0.0" />
    <PackageReference Include="FluentEmail.SendGrid" Version="3.0.2" />
    <PackageReference Include="SendGrid.Net40" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Migrations\" />
  </ItemGroup>
</Project>
