export const countries = [
  "Việt Nam",
  "Thái Lan",
  "Singapore",
  "Lào",
  "Campuchia",
  "Philipines",
  "Malaysia",
  "Myanmar",
  "Indonesia",
  "Trung Quốc",
  "Hàn Quốc",
  "Nhật Bản",
  "Ấn Độ",
  "Úc",
  "New Zealand",
  "Hoa Kỳ",
  "Canada",
  "Vương quốc Anh",
  "Pháp",
  "Đức",
  "Ý",
  "Hà Lan",
  "Khác",
  "Afghanistan",
  "Ai Cập",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anh Quốc",
  "Antigua và Barbuda",
  "Argentina",
  "Armenia",
  "Azerbaijan",
  "Áo",
  "Ả Rập Xê Út",
  "Bahamas",
  "Bahrain",
  "Ba Lan",
  "Bangladesh",
  "Barbados",
  "Bắc Macedonia",
  "Belarus",
  "Belize",
  "Benin",
  "Bhutan",
  "Bỉ",
  "Bolivia",
  "Bosnia và Herzegovina",
  "Botswana",
  "Bồ Đào Nha",
  "Bờ Biển Ngà",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cameroon",
  "Cape Verde",
  "Các Tiểu vương quốc Ả Rập Thống nhất",
  "Chile",
  "Colombia",
  "Comoros",
  "Cộng hòa Dân chủ Congo",
  "Cộng hòa Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Djibouti",
  "Dominica",
  "Cộng hòa Dominicana",
  "Đan Mạch",
  "Đông Timor",
  "Ecuador",
  "El Salvador",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Gabon",
  "Gambia",
  "Ghana",
  "Grenada",
  "Gruzia",
  "Guatemala",
  "Guinea",
  "Guinea Bissau",
  "Guinea Xích Đạo",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Hy Lạp",
  "Iceland",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Jamaica",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Latvia",
  "Liban",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Litva",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Maldives",
  "Malta",
  "Maroc",
  "Quần đảo Marshall",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Mozambique",
  "Mông Cổ",
  "Namibia",
  "Nam Phi",
  "Nam Sudan",
  "Nauru",
  "Na Uy",
  "Nepal",
  "Nga",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Phần Lan",
  "Philippines",
  "Qatar",
  "Romania",
  "Rwanda",
  "Saint Kitts và Nevis",
  "Saint Lucia",
  "Saint Vincent và Grenadines",
  "Samoa",
  "San Marino",
  "São Tomé và Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Cộng hòa Séc",
  "Sierra Leone",
  "Síp",
  "Slovakia",
  "Slovenia",
  "Quần đảo Solomon",
  "Somalia",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Tây Ban Nha",
  "Tchad",
  "Thổ Nhĩ Kỳ",
  "Thụy Điển",
  "Thụy Sĩ",
  "Togo",
  "Tonga",
  "Triều Tiên",
  "Trinidad và Tobago",
  "Cộng hòa Trung Phi",
  "Tunisia",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraina",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Thành Vatican",
  "Venezuela",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
